backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala, cli/src/main/scala/aqua/AquaCli.scala, model/src/main/scala/aqua/model/transform/BodyConfig.scala, model/src/main/scala/aqua/model/transform/Transform.scala
Fixes #67 : to compile for scripts storage, use CLI with `--no-xor --no-relay --air` flags and take a function with no arguments.
Should be further improved, but fills the hole right now.
Starting with this version, `aqua` can target Typescript, fldist, and script storage on nodes.
=> Config options to omit xor wrapper, relay passing

README.md, backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala, model/src/main/scala/aqua/model/transform/BodyConfig.scala, model/src/test/scala/aqua/model/Node.scala, model/src/test/scala/aqua/model/transform/TransformSpec.scala
Fldist might need to be changed. Relay name is a part of the configuration in `BodyConfig`, will be configurable with #76
=> Fixes #99: use impossible name for relay

model/src/main/scala/aqua/model/func/body/FuncOps.scala, model/src/main/scala/aqua/model/transform/ErrorsCatcher.scala, model/src/main/scala/aqua/model/transform/Transform.scala, model/src/test/scala/aqua/model/Node.scala, model/src/test/scala/aqua/model/transform/TransformSpec.scala
Helps with getting back with error from every node.
Might need further improvement:
- Fire-and-forget semantics, when we have it, means that we don't want to get errors back
- Error handling might provide unnecessary/inefficient hops
These improvements are mostly topological and are affected by #102.
=> Wrap every OnTag (topological shift) with Xor

types/src/main/scala/aqua/types/Type.scala
Might break some existing code that uses `s...` types. Required change: replace `s...` with `i...` in types.
=> Rename signed types to `i...`

aqua-src/error.aqua, backend/air/src/main/scala/aqua/backend/air/AirGen.scala, build.sbt, model/src/main/scala/aqua/model/func/body/FuncOp.scala, model/src/main/scala/aqua/model/func/body/OpTag.scala, model/src/main/scala/aqua/model/transform/ErrorsCatcher.scala, parser/src/main/scala/aqua/parser/expr/ForExpr.scala, parser/src/main/scala/aqua/parser/expr/FuncExpr.scala, parser/src/main/scala/aqua/parser/expr/IfExpr.scala, parser/src/main/scala/aqua/parser/expr/OnExpr.scala, parser/src/main/scala/aqua/parser/expr/TryExpr.scala, semantics/src/main/scala/aqua/semantics/ExprSem.scala, semantics/src/main/scala/aqua/semantics/expr/IfSem.scala, semantics/src/main/scala/aqua/semantics/expr/TrySem.scala
Related to #28 (no catch syntax yet).
Now you can use `try` this way:
```python
try:
Op.identity()
```
If the block fails, it will not affect execution. If you want to recover, use `otherwise`:
```python
try:
Op.identity()
otherwise:
on smth:
Op.identity()
```
=> Try expression added

.github/workflows/release.yml
You can now create releases manually. It will trigger npm publishing and then create a public github release. You can specify any branch including `main`.
=> Add a button for creating releases manually

aqua-src/error.aqua, backend/air/src/main/scala/aqua/backend/air/AirGen.scala, backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala, build.sbt, model/src/main/scala/aqua/model/func/body/FuncOps.scala, model/src/main/scala/aqua/model/transform/ArgsProvider.scala, parser/src/main/scala/aqua/parser/lexer/TypeToken.scala, semantics/src/main/scala/aqua/semantics/expr/DeclareStreamSem.scala, semantics/src/main/scala/aqua/semantics/expr/ForSem.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala, types/src/main/scala/aqua/types/Type.scala, types/src/test/scala/aqua/types/TypeSpec.scala
Fixes #108.
With this PR you can use option types in arguments, return values, and complex types. The syntax is the following:
```python
func usingOptions(optString: ?string) -> ?string:
-- Force the element, will throw if the value is empty
Peer.is_connected(optString!)
<- optString
```
Returning values from different branches, as expressed in #108, can be achieved using streams and bang operator:
```python
func returnFromBranches() -> bool:
ret: *bool
-- Can also be ret: ?bool
if true == false:
ret <- Peer.is_connected()
else:
ret <- Some.falsy()
<- ret!
```
A stream can be provided in place of option value:
```python
func returnFromBranches() -> ?bool:
ret: *bool
try:
ret <- Peer.is_connected()
<- ret
```
Providing an optional value with a checked one-shot resolution in the scope will …
=> 108 option type

.github/workflows/test_branch.yml, cli/src/main/scala/aqua/AppOps.scala, cli/src/main/scala/aqua/AquaCli.scala, model/src/main/scala/aqua/model/transform/BodyConfig.scala, parser/src/main/scala/aqua/parser/expr/ConstantExpr.scala
fixes #170 
Usage:
You can override constants with a question mark or use inexistent constants here:
```
import "@fluencelabs/aqua-lib/builtin.aqua"
service Cast("test"):
-- create string from u32
str: u32 -> string
service OpO("op"):
identity: string -> string
const anotherConst ?= "default-str"
func callConstant() -> []string:
res: *string
res <- Cast.str(uniqueConst)
res <- OpO.identity(anotherConst)
<- res
```
with:
```
java ...  -c "uniqueConst = 1" -c "anotherConst = \"ab\""
```
The result will be `['1', 'ab']`
=> 170 pass constants as arguments

backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
`config?.ttl` syntax isn't supported on older TypeScript versions
=> Use backwards compatible syntax for config.ttl

aqua-src/test.aqua, model/src/main/scala/aqua/model/func/FuncCallable.scala, model/src/main/scala/aqua/model/func/raw/FuncOp.scala
```
service AquaDHT("aqua-dht"):
put_host_value(key: string, value: string, service_id: []string)
func putHostValue(key: string, value: string, service_id: ?string):
AquaDHT.put_host_value(key, value, service_id)
func create_client_util(service_id: string):
putHostValue("client-util", service_id, nil)
```
This code should be compiled with correct arguments
```
(xor
(seq
(seq
(call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
(call %init_peer_id% ("getDataSrv" "service_id") [] service_id)
)
(call %init_peer_id% ("aqua-dht" "put_host_value") ["client-util" service_id $nil])
)
(call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
)
```
=> Fix incorrect compilation with arguments duplication

.github/workflows/release.yml
I've left `on push` by mistake in #220. This PR removes it, so release happens only on a button click in Actions.
P.S. Keep in mind that the current release workflow doesn't play well with releases on the same x.y.z version, i.e. it spams the changelog. AFAIK this is OK since it's not intended to be used this way.
=> CI: Do not trigger releases on push

backend/ts/src/main/scala/aqua/backend/ts/TSServiceTypes.scala, types/src/main/scala/aqua/types/CompareTypes.scala
Make it possible to pass `?u8` as `?u32` argument
fixes #343
=> #343 Compare option types properly

aqua-src/restrict.aqua, backend/air/src/main/scala/aqua/backend/air/Air.scala, backend/air/src/main/scala/aqua/backend/air/AirGen.scala, build.sbt, cli/.jvm/src/main/scala/aqua/Test.scala, model/src/main/scala/aqua/model/func/FuncCallable.scala, model/src/main/scala/aqua/model/func/raw/FuncOp.scala, model/src/main/scala/aqua/model/func/raw/RawTag.scala, model/test-kit/src/test/scala/aqua/model/transform/topology/RawCursorSpec.scala, model/test-kit/src/test/scala/aqua/model/transform/topology/TopologySpec.scala, model/transform/src/main/scala/aqua/model/transform/res/CallRes.scala, model/transform/src/main/scala/aqua/model/transform/res/MakeRes.scala, model/transform/src/main/scala/aqua/model/transform/res/ResolvedOp.scala, model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala, semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/ForSem.scala, semantics/src/main/scala/aqua/semantics/rules/names/NamesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala, types/src/main/scala/aqua/types/Type.scala
Fixes #321
Should be merged & released After the updated AquaVM is delivered to the node, to fluence-js, and Aqua's internal fluence-js dependency is updated accordingly.
=> #321 restricted stream scopes

cli/.js/src/main/scala/aqua/RunCommand.scala
Right now you cannot check what peerId you use on a running script. Add it to output
=> Add init_peer_id in output

cli/.js/src/main/scala/aqua/run/RunWrapper.scala
This code throws an error on `aqua run`, but it is valid
```
import Srv, Service from "@fluencelabs/aqua-lib/builtin.aqua"
func list() -> []Service:
on HOST_PEER_ID:
result <- Srv.list()
<- result
```
PR fixes it
=> Fix error when no variables in arguments

.github/workflows/release.yml, build.sbt
There is an error on any command
```
"@fluencelabs/aqua": "^0.5.2-252"
> aqua -i aqua -o generated
node:internal/errors:464
ErrorCaptureStackTrace(err);
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/aleksey/Documents/dev/fluencelabs/trust-graph/example/node_modules/@fluencelabs/aqua/dist/ipfs.js' imported from /Users/aleksey/Documents/dev/fluencelabs/trust-graph/example/node_modules/@fluencelabs/aqua/aqua.js
at new NodeError (node:internal/errors:371:5)
at finalizeResolution (node:internal/modules/esm/resolve:392:11)
at moduleResolve (node:internal/modules/esm/resolve:899:10)
at defaultResolve (node:internal/modules/esm/resolve:1011:11)
at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
at …
```
=> Fix publishing

aqua-src/nopingback.aqua, model/test-kit/src/test/scala/aqua/model/transform/topology/TopologySpec.scala, model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala
Fixes topology for `co`, but adds one unnecessary `noop` call. Not sure how to remove it.
=> Fixes topology for co

aqua-src/nopingback.aqua, build.sbt, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala, model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala, model/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/src/main/scala/aqua/model/inline/Sugar.scala, model/transform/src/main/scala/aqua/model/transform/res/MakeRes.scala, parser/src/main/scala/aqua/parser/lexer/LambdaOp.scala, parser/src/main/scala/aqua/parser/lexer/Token.scala, semantics/src/main/scala/aqua/semantics/expr/ConstantSem.scala, semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/AbilityIdSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/AssignmentSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/CallArrowSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/ForSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/IfSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/OnSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/PushToStreamSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/ReturnSem.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
Fixes #329 
To use non-literal indices, the new brackets syntax is introduced:
```python
opt: []string
-- Take an element of an array, or 0 element
opt!
-- Take the sixth element
opt!5 
-- the same as opt!
opt[0]
-- the same as opt!5
opt[5]
-- get by index
func get(idx: i16) -> string:
<- opt[idx]
-- Can use any proper value getter as an argument
get(opt!)
data Complex:
field: []i16
func other(c: Complex) -> string
x <- get(c.field!55)
<- x
```
=> Scalar index access

.scalafmt.conf, cli/.js/src/main/scala/aqua/builder/ArgumentGetter.scala, cli/.js/src/main/scala/aqua/run/RunOpts.scala, cli/.js/src/main/scala/aqua/run/Runner.scala
Variables were not registered in air
```
aqua run -i aqua-scripts -a /dns4/kras-00.fluence.dev/tcp/19990/wss/p2p/12D3KooWSD5PToNiLQwKDXsu8JSysCwUt8BVUJEqCHcDe7P5h45e -f 'add_one(arg1, arg2, arg3)' --data '{"arg1": 5, "arg2": "12D3KooWFtf3rfCDAfWwt6oLZYZbDfn9Vn7bv7g6QjjQxUUEFVBt", "arg3": "7b2ab89f-0897-4537-b726-8120b405074d"}'
Your peerId: 12D3KooWMHpKgiGaduHWhW3pJdCEoQUjR8wrQsZm1cKxhkrgxB8L
Interpreter failed:  {
"retCode": 1,
"errorMessage": "air can't be parsed:\nerror: \n   ┌─ script.air:11:7\n   │\n11 │       (call arg2 (arg3 \"add_one\") [arg1] res)\n   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   │       │\n   │       variable 'arg2' wasn't defined\n   │       variable 'arg3' wasn't defined\n   │       variable 'arg1' wasn't defined\n\n",
"data": "",
"nextPeerPks": [], …
```
=> Arguments from the console did not pass to air

model/transform/src/main/scala/aqua/model/transform/res/MakeRes.scala
`identity` doesn't support multiple arguments. Change to `noop`
=> Use `noop` call on `join`

build.sbt, cli/.js/src/main/scala/aqua/ArgOpts.scala, cli/.js/src/main/scala/aqua/dist/DistOpts.scala, cli/.js/src/main/scala/aqua/js/FluenceJsTypes.scala, cli/.js/src/main/scala/aqua/run/FuncCaller.scala, cli/.js/src/main/scala/aqua/run/RunConfig.scala, cli/.js/src/main/scala/aqua/run/RunOpts.scala, cli/.js/src/main/scala/aqua/run/Runner.scala, cli/.jvm/src/main/scala/aqua/PlatformOpts.scala, cli/src/main/scala/aqua/AppOpts.scala, cli/src/main/scala/aqua/FileOpts.scala, cli/src/main/scala/aqua/FluenceOpts.scala, model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala, npm/aqua/dist.aqua
=> Remove service command, file options refactoring

cli/.js/src/main/scala/aqua/run/FuncCaller.scala, npm/aqua/dist.aqua, npm/src/config.ts
fixes #436 
also adds missed fields to ModuleConfig in `aqua dist deploy`, related to #421
=> Add timeout to finisher to avoid infinite hanging of async functions

build.sbt, cli/.js/src/main/scala/aqua/builder/Console.scala, parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
Support top-bottom notation to make it possible to work with `any` type. Useful for debug tools as:
```
service Debug("debug"):
stringify(o: ⊤) -> string
```
=> Add top-bottom support

aqua-src/hack.aqua, model/res/src/main/scala/aqua/res/MakeRes.scala, parser/src/main/scala/aqua/parser/lexer/Token.scala, parser/src/main/scala/aqua/parser/lexer/ValueToken.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala
Use `[]` to create an empty array. Should be useful when you play with collection creation syntax, adding and removing elements from square braces.
=> Empty collections creation

build.sbt, cli/.js/src/main/scala/aqua/PlatformOpts.scala, cli/src/main/scala/aqua/Prelude.scala, parser/src/main/scala/aqua/parser/Parser.scala, project/plugins.sbt, semantics/src/main/scala/aqua/semantics/expr/func/IfSem.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, types/src/main/scala/aqua/types/CompareTypes.scala
=> Use global `node_modules` path to find aqua dependencies

cli/.js/src/main/scala/aqua/ArgOpts.scala, cli/.js/src/main/scala/aqua/ipfs/IpfsOpts.scala, model/src/main/scala/aqua/model/ValueModel.scala
It fixes types resolving in `aqua run` for a case where argument uses for `via` route
=> Set arguments types dynamically from JSON

npm/index.js
=> #460 Fix handling short pipes in `aqua cli`

build.sbt, cli/.js/src/main/scala/aqua/ArgOpts.scala, cli/.js/src/main/scala/aqua/CommandBuilder.scala, cli/.js/src/main/scala/aqua/builder/IPFSUploader.scala, cli/.js/src/main/scala/aqua/json/JsonEncoder.scala, cli/.js/src/main/scala/aqua/run/Runner.scala, cli/.js/src/test/scala/aqua/JsonEncoderSpec.scala, cli/src/main/scala/aqua/AquaCli.scala, cli/src/main/scala/aqua/io/OutputPrinter.scala, types/src/main/scala/aqua/types/CompareTypes.scala
fixes #435 
If you will pass JSON with absent fields you will get an error.
For example:
```
aqua run -f 'identityArgsAndReturn(structField)'...
```
Where `structField` should be type of `StructType`:
```
data SubType:
a: ?string
b: []u32
c: string
d: string
data StructType:
numField: u32
arrField: []string
arr2: []SubType
```
And we pass JSON where field `arr2` have objects with missed fields:
```
{
"structField": {
"numField": 42,
"arrField": ["str1", "str2", "r43r34", "ferer"],
"arr2": [{
"a": "fef",
"b": [1,2,3,4],
"c": "erfer"
},{
"b": [1,2,3,4],
"c": "erfer"
}, {
"a": "as",
"d": "gerrt"
}]
}
}
```
We will get an error that points to these fields
```
Type for field 'structField.arr2.c' mismatch with argument. Expected: 'string' Given: '?string'
Type for field 'structField.arr2.d' …
```
=> Generate types from JSON

parser/src/main/scala/aqua/parser/expr/ConstantExpr.scala
Arrays are not literals and need to generate operations in air code. It is unclear right now how to do this properly. This PR will add clear error messages for this.
```
---- Syntax error: /home/diemust/git/aqua/npm/test/sample.aqua:20:26
20 const AAA = ["a", "b"]
^
The constant cannot be an array
```
=> Show parser error if constant is an array, function call, or expression

cli/.js/src/main/scala/aqua/ArgOpts.scala
Example:
```
aqua run -f 'someFunc(["str", "another str"])'
```
=> Pass arrays as arguments in `aqua run` function call

cli/.js/src/main/scala/aqua/ArgOpts.scala, cli/.js/src/main/scala/aqua/FuncCompiler.scala, cli/.js/src/main/scala/aqua/builder/IPFSUploader.scala, cli/.js/src/main/scala/aqua/config/ConfigOpts.scala, cli/.js/src/main/scala/aqua/json/JsonEncoder.scala, cli/.js/src/main/scala/aqua/keypair/KeyPairOpts.scala, cli/.js/src/main/scala/aqua/remote/DistOpts.scala, cli/.js/src/main/scala/aqua/run/FuncCaller.scala, cli/.js/src/main/scala/aqua/run/RunConfig.scala, cli/.js/src/main/scala/aqua/run/Runner.scala, cli/.js/src/main/scala/aqua/script/ScriptOpts.scala, cli/.jvm/src/main/scala/aqua/Test.scala, cli/src/main/scala/aqua/AppOpts.scala, cli/src/main/scala/aqua/AquaCli.scala, cli/src/main/scala/aqua/FileOpts.scala, cli/src/main/scala/aqua/FluenceOpts.scala
Please check if it compiles (I didn't bother installing scala but maybe I should) and also check if I didn't mess up the meaning. Thanks!
=> Attempt to make cli messages better

cli/.js/src/main/scala/aqua/CommandBuilder.scala, cli/src/main/scala/aqua/AquaCli.scala
=> Don't print help on errors in CLI

cli/.js/src/main/scala/aqua/CommandBuilder.scala, cli/.js/src/main/scala/aqua/LogLevelTransformer.scala, cli/.js/src/main/scala/aqua/js/FluenceJsTypes.scala, cli/.js/src/main/scala/aqua/run/FuncCaller.scala, cli/.js/src/main/scala/aqua/run/RunCommand.scala, cli/.js/src/main/scala/aqua/run/RunConfig.scala, cli/.js/src/main/scala/aqua/run/RunOpts.scala, cli/src/main/scala/aqua/FluenceOpts.scala
Format: `'<log-level>' or 'compiler=<log-level>,fluencejs=<log-level>,aquavm=<log-level>', where <log-level> is one of these strings: 'all', 'trace', 'debug', 'info', 'warn', 'error', 'off'`
=> LNG-64 Configurable log-level argument

cli/.js/src/main/scala/aqua/json/TypeValidator.scala, cli/.js/src/test/scala/aqua/TypeValidatorSpec.scala
`OptionType(string)` in aqua is equal as `string | undefined` in JSON
`ArrayType(string)` in aqua is equal as `string[]` in JSON
`Option(ArrayType(string))` in aqua is equal as `string[] | undefined` in JSON
etc...
=> Type validation for types generated from JSON

.github/workflows/release.yml
Bump aqua-api npm version in release-please PR to use aqua-api from workspace.
=> chore(release-please): Set aqua-api version in tests

integration-tests/aqua/examples/topology.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/topologyCall.ts, model/transform/src/main/scala/aqua/model/transform/cursor/ChainCursor.scala, model/transform/src/main/scala/aqua/model/transform/topology/OpModelTreeCursor.scala, model/transform/src/main/scala/aqua/model/transform/topology/PathFinder.scala, model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala, model/transform/src/main/scala/aqua/model/transform/topology/strategy/After.scala, model/transform/src/main/scala/aqua/model/transform/topology/strategy/XorBranch.scala, model/transform/src/test/scala/aqua/model/transform/topology/TopologySpec.scala
* Update topology: while computing `pathAfter`, find next `ForceExecModel` and generate exit to relay if its `pathOn` does not match our `afterOn` (it means that more hops will be done to reach it.
* Add unit and integration tests
=> fix(compiler): Fix topology for adjacent `on`s [LNG-257]

aqua-src/antithesis.aqua, integration-tests/aqua/examples/abilities.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/abilityCall.ts, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/inline/src/main/scala/aqua/model/inline/Inline.scala, model/inline/src/main/scala/aqua/model/inline/TagInliner.scala, model/inline/src/main/scala/aqua/model/inline/raw/ApplyPropertiesRawInliner.scala, model/inline/src/main/scala/aqua/model/inline/raw/CallArrowRawInliner.scala, model/inline/src/main/scala/aqua/model/inline/raw/MakeAbilityRawInliner.scala, model/inline/src/test/scala/aqua/model/inline/TagInlinerSpec.scala, model/raw/src/main/scala/aqua/raw/value/PropertyRaw.scala, model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala, parser/src/main/scala/aqua/parser/expr/func/CallArrowExpr.scala, semantics/src/main/scala/aqua/semantics/expr/func/CallArrowSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/ClosureSem.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala
After this PR functions in abilities can be called with `<-` symbol, as common functions.
```
func create() -> TestAb:
arrow = () -> i8, i8:
<- 42, 76
<- TestAb(inner = InnerAb(arrow = arrow))
func test() -> i8, i8:
ababab <- create()
res1, res2 <- ababab.inner.arrow()
<- res1, res2
```
Handle `ApplyPropertyRaw` with `IntoArrowRaw` for `CallArrowRawTag`
=> fix(compiler): Return ability arrow [LNG-258]

parser/src/main/scala/aqua/parser/lexer/NamedArg.scala, parser/src/main/scala/aqua/parser/lexer/PropertyOp.scala, parser/src/main/scala/aqua/parser/lexer/Token.scala, parser/src/main/scala/aqua/parser/lexer/ValueToken.scala, parser/src/test/scala/aqua/parser/AbilityValueExprSpec.scala, parser/src/test/scala/aqua/parser/StructValueExprSpec.scala, parser/src/test/scala/aqua/parser/lexer/PropertyOpSpec.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala
Allow omitting field name in ability or data construction if it is the same as the passed variable for convenience:
```
field = 42
st = Struct(field) -- same as Struct(field = field)
```
Also the same for `.copy` method.
* Rewrite parsing to accept short arguments in `.copy` and constructors
* Process parsing results on semantics stage accordingly
=> feat(compiler): Allow omitting field name in struct creation [LNG-261]

aqua-src/antithesis.aqua, integration-tests/aqua/examples/abilities.aqua, integration-tests/aqua/examples/closures.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/abilityCall.ts, integration-tests/src/examples/closures.ts, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala, semantics/src/main/scala/aqua/semantics/ExprSem.scala, semantics/src/main/scala/aqua/semantics/RawSemantics.scala, semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala
Returning multiple closures from one function generates incorrect AIR
```
func create(a: i8, b: i8) -> i8 -> i8, i8:
arrow = (c: i8) -> i8, i8:
<- a, b
<- arrow
func test() -> i8, i8, i8, i8, i8, i8:
Ab <- create(1, 2)
ab <- create(3, 4)
AB <- create(5, 6)
<- res1, res2, res3, res4, res5, res6
```
There were two problems:
- return value names weren't renamed in ArrowInliner
- generated in ArrowSem names overlapped
=> fix(compiler): Multiple closures in one function [LNG-262]

aqua-src/antithesis.aqua, model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, semantics/src/test/scala/aqua/semantics/ValuesAlgebraSpec.scala
Throw compilation error on a code like this:
```
alias NamedT: u32
func test():
MyAbility = NamedT(randomField = "sf")
```
Don't ignore named type comparison with aliases, improve type checking error.
=> fix(compiler): Throw an error when comparing an alias and a named type with the same name [LNG-231]

backend/air/src/main/scala/aqua/backend/air/Air.scala, backend/air/src/main/scala/aqua/backend/air/AirGen.scala, compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala, model/inline/src/main/scala/aqua/model/inline/TagInliner.scala, model/inline/src/main/scala/aqua/model/inline/raw/StreamGateInliner.scala, model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala, model/res/src/main/scala/aqua/res/MakeRes.scala, model/res/src/main/scala/aqua/res/ResolvedOp.scala, model/res/src/test/scala/aqua/res/ResBuilder.scala, model/src/main/scala/aqua/model/OpModel.scala, model/transform/src/main/scala/aqua/model/transform/pre/ArgsProvider.scala, model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala, model/transform/src/test/scala/aqua/model/transform/ModelBuilder.scala, model/transform/src/test/scala/aqua/model/transform/topology/OpModelTreeCursorSpec.scala, model/transform/src/test/scala/aqua/model/transform/topology/TopologySpec.scala, semantics/src/main/scala/aqua/semantics/expr/func/ForSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/ParSeqSem.scala, semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala
Always generate `last` argument of `fold` instruction in result AIR to make this explicit.
Removal of `Option` for `for` and `fold` models
Self-descriptive
=> feat(compiler): Always generate `last` argument of `fold` [LNG-265]

semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala, types/src/main/scala/aqua/types/Type.scala, utils/helpers/src/main/scala/aqua/syntax/optiont.scala
Report compilation errors on call to not existing method of ability or service.
Refactor `CallArrowRaw` generation, add error report.
=> fix(compiler): Unknown service method call is ignored [LNG-273]

.scalafmt.conf, aqua-src/antithesis.aqua, io/src/main/scala/aqua/Rendering.scala, io/src/test/scala/aqua/RenderingSpec.scala, parser/src/main/scala/aqua/parser/Parser.scala, parser/src/main/scala/aqua/parser/lift/Span.scala, parser/src/test/scala/aqua/parser/FuncExprSpec.scala
```
func arr(strs: []string) -> []string
<- strs
```
this code throws `StringOutOfBound` instead of parser error 
Pad strings that the compiler error renderer can point.
=> fix(compiler): Incorrect focus on error [LNG-274]

aqua-src/antithesis.aqua, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/inline/src/main/scala/aqua/model/inline/TagInliner.scala, model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala, model/transform/src/main/scala/aqua/model/transform/pre/FuncPreTransformer.scala, semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala
```
func returnNil() -> *string:
someStr: *string
<- someStr
func newFunc():
...
stream <- returnNil() -- here compiler makes a restriction for the stream before calling this arrow
-- should be a mechanism that can inline tag after inlining its children
...
```
Add `After` for `TagInlined` that will be called after all children inlined.
=> fix(compiler): Code generate wrong stream name in AIR [LNG-276]

api/api-npm/index.d.ts, api/api-npm/index.js, api/api/.js/src/main/scala/api/types/InputTypes.scala, api/api/src/main/scala/aqua/api/AquaAPIConfig.scala, compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala, model/transform/src/main/scala/aqua/model/transform/Transform.scala, model/transform/src/main/scala/aqua/model/transform/TransformConfig.scala, model/transform/src/main/scala/aqua/model/transform/pre/ResultsHandler.scala, model/transform/src/test/scala/aqua/model/transform/ModelBuilder.scala, model/transform/src/test/scala/aqua/model/transform/TransformSpec.scala
Generate empty call to reponse service if there are no return values so that js-client could know if execution finished.
=> feat(compiler): Generate empty calls to `responseHandlerSrv` [LNG-286]

.github/workflows/e2e.yml, js/js-exports/src/main/scala/aqua/js/Definitions.scala
Use `js.UndefOr` for `defaultServiceId` for easy of use in ts.
=> feat(api): Use `js.UndefOr` for `defaultServiceId`

.github/workflows/e2e.yml
Use `main` branch for `fcli` in e2e github workflow
=> fix(e2e): Use `main` branch for `fcli`

aqua-src/antithesis.aqua, integration-tests/aqua/examples/closures.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/closures.ts, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/raw/src/main/scala/aqua/raw/arrow/FuncRaw.scala, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala
Nested closures cannot find arrows on inline step
Add correct context to closures.
=> fix(compiler): Add outside context to closures [LNG-317]

aqua-src/antithesis.aqua, backend/air/src/main/scala/aqua/backend/air/Air.scala, integration-tests/aqua/examples/closures.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/closures.ts, model/inline/src/main/scala/aqua/model/inline/RawValueInliner.scala, model/inline/src/main/scala/aqua/model/inline/TagInliner.scala, model/inline/src/main/scala/aqua/model/inline/tag/IfTagInliner.scala, model/raw/src/main/scala/aqua/raw/ops/Call.scala, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala, model/src/main/scala/aqua/model/FuncArrow.scala, semantics/src/main/scala/aqua/semantics/expr/func/CallArrowSem.scala, semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala, types/src/main/scala/aqua/types/Type.scala, utils/mangler/src/main/scala/aqua/mangler/ManglerState.scala
Compiler renames exported stream in a wrong way.
Exports must be inlined as all variables for correct renaming.
=> fix(compiler): Streams in closures generates wrong AIR

aqua-src/antithesis.aqua, aqua-src/export.aqua, language-server/language-server-api/src/main/scala/aqua/lsp/LocationsInterpreter.scala, language-server/language-server-api/src/test/scala/aqua/lsp/AquaLSPSpec.scala, parser/src/main/scala/aqua/parser/expr/func/ArrowExpr.scala, parser/src/main/scala/aqua/parser/lexer/TypeToken.scala, parser/src/test/scala/aqua/AquaSpec.scala, parser/src/test/scala/aqua/parser/ArrowTypeExprSpec.scala, parser/src/test/scala/aqua/parser/lexer/TypeTokenSpec.scala, semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/CallArrowSem.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypeResolution.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesAlgebra.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala, semantics/src/test/scala/aqua/semantics/TypeResolutionSpec.scala
Use `strict` to prevent registering types when there is types with the same name imported from another file.
Also, fix token locations for services, abilities and structures.
fixes LNG-334
fixes LNG-335
fixes LNG-336
fixes LNG-299
fixes LNG-300
=> fix(compiler): Use `strict` to check types availability [LNG-334]

aqua-src/antithesis.aqua, integration-tests/aqua/examples/abilitiesClosure.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/abilityClosureCall.ts, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala
Pass abilities contexts that is used in arrows in other abilities
=> fix(compiler): Recursively find abilities [LNG-338]

.github/workflows/e2e.yml, aqua-src/antithesis.aqua, aqua-src/hack.aqua, language-server/language-server-api/src/main/scala/aqua/lsp/LspSemantics.scala, language-server/language-server-api/src/test/scala/aqua/lsp/AquaLSPSpec.scala, semantics/src/main/scala/aqua/semantics/expr/func/FuncSem.scala
Name clashing only in LSP if there is equal function names in imported and current files.
=> fix(language-server): Name clashing in LSP [LNG-342]

parser/src/main/scala/aqua/parser/head/ModuleExpr.scala, parser/src/main/scala/aqua/parser/lexer/Token.scala, parser/src/test/scala/aqua/parser/head/ModuleSpec.scala
Fix parsing so that it allows additional spaces after `aqua` header
=> fix: Allow spaces after aqua header

compiler/src/main/scala/aqua/compiler/AquaCompiler.scala, compiler/src/main/scala/aqua/compiler/CompilerAPI.scala, language-server/language-server-api/src/main/scala/aqua/lsp/LSPCompiler.scala, language-server/language-server-api/src/main/scala/aqua/lsp/LspContext.scala, language-server/language-server-api/src/main/scala/aqua/lsp/LspSemantics.scala, model/raw/src/main/scala/aqua/raw/Raw.scala, model/raw/src/main/scala/aqua/raw/RawContext.scala, model/raw/src/main/scala/aqua/raw/RawPart.scala, model/src/main/scala/aqua/model/AquaContext.scala, semantics/src/main/scala/aqua/semantics/CompilerState.scala, semantics/src/main/scala/aqua/semantics/RawSemantics.scala, semantics/src/main/scala/aqua/semantics/header/ExportSem.scala, semantics/src/main/scala/aqua/semantics/header/HeaderHandler.scala, semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala, semantics/src/main/scala/aqua/semantics/header/ModuleSem.scala, semantics/src/main/scala/aqua/semantics/header/Picker.scala, semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesState.scala, semantics/src/main/scala/aqua/semantics/rules/names/NamesState.scala, semantics/src/main/scala/aqua/semantics/rules/report/ReportState.scala, semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala, semantics/src/test/scala/aqua/semantics/HeaderSpec.scala, utils/mangler/src/main/scala/aqua/mangler/ManglerState.scala
Refactor `HeaderSem`, removing unnecessary code and simplifying it.
- Simplify `HeaderSem`
- Refactor `RawContext`
- Refactor `RawSemantics`
=> fix(compiler): Refactor header semantics [LNG-352]

aqua-src/antithesis.aqua, language-server/language-server-api/src/main/scala/aqua/lsp/LspContext.scala, language-server/language-server-api/src/main/scala/aqua/lsp/LspSemantics.scala, language-server/language-server-api/src/test/scala/aqua/lsp/AquaLSPSpec.scala, model/raw/src/main/scala/aqua/raw/ErroredPart.scala, model/raw/src/main/scala/aqua/raw/RawContext.scala, semantics/src/main/scala/aqua/semantics/RawSemantics.scala, semantics/src/main/scala/aqua/semantics/Semantics.scala, semantics/src/main/scala/aqua/semantics/expr/AbilitySem.scala, semantics/src/main/scala/aqua/semantics/expr/AliasSem.scala, semantics/src/main/scala/aqua/semantics/expr/ConstantSem.scala, semantics/src/main/scala/aqua/semantics/expr/DataStructSem.scala, semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala, semantics/src/main/scala/aqua/semantics/expr/func/FuncSem.scala
VSCode shows incorrect errors in exported functions
Turn state with errors to `CompileError`
Because lsp creates context on errors too, it breaks on finalising headers and shows incorrect error.
=> fix(compiler): Return error if SemanticError occures [LNG-356]

compiler/src/main/scala/aqua/compiler/CompilerAPI.scala, compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala, model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala, model/inline/src/main/scala/aqua/model/inline/TagInliner.scala, model/src/main/scala/aqua/model/AquaContext.scala, model/src/main/scala/aqua/model/ValueModel.scala, semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala
Add support for redeclaring imported services in an aqua module.
Example:
`import1.aqua`:
```aqua
aqua Import1 declares Srv
service Srv("srv-id"):
call()
```
`import2.aqua`:
```aqua
aqua Import2 declares Import1.Srv
use "import1.aqua"
```
`main.aqua`:
```aqua
aqua Main
export main
use "import2.aqua"
func main():
Import2.Import1.Srv.call()
```
Gather all services in `AquaContext` to pass them to `FuncRaw`.
=> feat(compiler): Allow redeclaring services (and abilities) [LNG-360]

api/api/.js/src/main/scala/api/types/InputTypes.scala, api/api/.js/src/main/scala/api/types/OutputTypes.scala, aqua-src/antithesis.aqua, js/js-exports/src/main/scala/aqua/js/Definitions.scala, language-server/language-server-api/.js/src/main/scala/aqua/lsp/OutputTypes.scala
Use js.Object instead of `JSExport` to create output classes with strict field names in JSON (without obfuscation)
=> feat(api, lsp): Case classes exported to JS as normal JSONs

aqua-src/antithesis.aqua, integration-tests/aqua/examples/closureReturnRename.aqua, integration-tests/src/__test__/examples.spec.ts, integration-tests/src/examples/closureReturnRename.ts, model/raw/src/main/scala/aqua/raw/ops/RawTag.scala
This didn't work:
```
func addToStreamClosure(str: *string) -> string -> ():
cl = func (s: string):
str <<- s
<- cl
func addToStream() -> []string:
stream: *string
cl = addToStreamClosure(stream)
cl("one")
<- stream
```
because `str` hasn't been renamed in inliner.
rename exports of closure body on `renameExports`
=> fix(compiler): Push to stream in closures [LNG-365]

semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala, types/src/main/scala/aqua/types/Type.scala
Fix compiler failing on such code:
```aqua
aqua Main
export main
func test(arr: []⊤) -> string:
<- "test"
func main() -> string:
map: %string
<- test([map])
```
Make `CollectibleType` more strict.
=> fix(compiler): Fix CRDT Map in array handling [LNG-370]
