build.sbt
parser/src/main/scala/aqua/parser/expr/ForExpr.scala
parser/src/test/scala/aqua/parser/ForExprSpec.scala
semantics/src/main/scala/aqua/semantics/expr/ForSem.scala

For...try expression

---

cli/src/main/scala/aqua/AquaCli.scala

CLI: Version flag and help flag must take precedence over everything else

---

aqua-src/error.aqua
backend/air/src/main/scala/aqua/backend/air/Air.scala
backend/air/src/main/scala/aqua/backend/air/AirGen.scala
model/src/main/scala/aqua/model/func/body/FuncOps.scala
model/src/main/scala/aqua/model/func/body/OpTag.scala
model/src/main/scala/aqua/model/topology/Cursor.scala
model/src/main/scala/aqua/model/topology/Topology.scala
model/src/main/scala/aqua/model/transform/ArgsProvider.scala
semantics/src/main/scala/aqua/semantics/expr/OnSem.scala

Support options for `via` clause in `on` expression

---

aqua-src/demo.aqua
backend/air/src/main/scala/aqua/backend/air/AirGen.scala
build.sbt
model/src/main/scala/aqua/model/ServiceModel.scala
model/src/main/scala/aqua/model/func/FuncCallable.scala
model/src/main/scala/aqua/model/func/body/FuncOp.scala
model/src/main/scala/aqua/model/func/body/OpTag.scala
model/src/main/scala/aqua/model/transform/Transform.scala
parser/src/main/scala/aqua/parser/expr/ForExpr.scala
parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
parser/src/main/scala/aqua/parser/expr/IfExpr.scala
parser/src/main/scala/aqua/parser/expr/OnExpr.scala
semantics/src/main/scala/aqua/semantics/ExprSem.scala
semantics/src/main/scala/aqua/semantics/expr/AbilityIdSem.scala
semantics/src/main/scala/aqua/semantics/expr/AssignmentSem.scala
semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesAlgebra.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilityOp.scala

AssignmentExpression

---

backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala

Generate optional ttl argument in typescript functions

---

aqua-src/demo.aqua
parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
parser/src/main/scala/aqua/parser/lexer/Token.scala
parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
parser/src/test/scala/aqua/parser/FuncExprSpec.scala

```
service TestS("some-id"):
multiline(a: string,
b: string,
c: bool) -> string
...
func doStuff(a: string,
b: string,
c: bool,
d: bool, e: []string, g: []string, str: string) -> []string:   
...
stream <- TestS.multiline(a,
b,
c) 
```

157 multiline function definitions

---

model/src/main/scala/aqua/model/func/Call.scala
model/src/main/scala/aqua/model/func/FuncCallable.scala
model/src/main/scala/aqua/model/func/body/FuncOp.scala
model/src/main/scala/aqua/model/func/body/OpTag.scala
model/src/main/scala/aqua/model/topology/Cursor.scala
model/src/main/scala/aqua/model/topology/Location.scala
model/src/main/scala/aqua/model/topology/Topology.scala
model/src/test/scala/aqua/model/Node.scala
model/src/test/scala/aqua/model/topology/TopologySpec.scala
model/src/test/scala/aqua/model/transform/TransformSpec.scala
semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala

Fixes #148 
Fixes #102
Supersedes #159

148 topology fix

---

backend/air/src/main/scala/aqua/backend/air/AirGen.scala
build.sbt
model/src/main/scala/aqua/model/func/raw/FuncOp.scala
model/src/main/scala/aqua/model/func/raw/FuncOps.scala
model/src/main/scala/aqua/model/func/raw/PathFinder.scala
model/src/main/scala/aqua/model/func/raw/RawCursor.scala
model/src/main/scala/aqua/model/func/raw/RawTag.scala
model/src/main/scala/aqua/model/topology/Topology.scala
parser/src/main/scala/aqua/parser/expr/CoExpr.scala
parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
parser/src/main/scala/aqua/parser/expr/IfExpr.scala
parser/src/main/scala/aqua/parser/expr/OnExpr.scala
parser/src/main/scala/aqua/parser/lexer/Token.scala
semantics/src/main/scala/aqua/semantics/ExprSem.scala
semantics/src/main/scala/aqua/semantics/expr/CoSem.scala

Co expression

---

aqua-src/test.aqua
backend/js/src/main/scala/aqua/backend/js/JavaScriptBackend.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
semantics/src/main/scala/aqua/semantics/Semantics.scala

Return `T | null` on optional results

---

aqua-src/test.aqua
build.sbt
model/src/main/scala/aqua/model/Model.scala
model/src/main/scala/aqua/model/ReturnModel.scala
model/src/main/scala/aqua/model/func/raw/FuncOps.scala
model/src/main/scala/aqua/model/func/raw/RawTag.scala
parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
semantics/src/main/scala/aqua/semantics/expr/FuncSem.scala
semantics/src/main/scala/aqua/semantics/expr/ReturnSem.scala

fixes #53 return literal only in functions
fixes #219 disable top-bottom parsing

53 219 issues

---

.github/workflows/release.yml
aqua-src/ret.aqua
backend/air/src/main/scala/aqua/backend/air/AirGen.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
build.sbt
model/src/main/scala/aqua/model/ReturnModel.scala
model/src/main/scala/aqua/model/transform/ResolveFunc.scala
parser/src/main/scala/aqua/parser/expr/ArrowTypeExpr.scala
parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
parser/src/main/scala/aqua/parser/expr/ReturnExpr.scala
parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
parser/src/test/scala/aqua/AquaSpec.scala
parser/src/test/scala/aqua/parser/ArrowTypeExprSpec.scala
parser/src/test/scala/aqua/parser/CallArrowSpec.scala
parser/src/test/scala/aqua/parser/CoExprSpec.scala
parser/src/test/scala/aqua/parser/FuncExprSpec.scala
parser/src/test/scala/aqua/parser/ParExprSpec.scala
parser/src/test/scala/aqua/parser/ReturnExprSpec.scala
parser/src/test/scala/aqua/parser/lexer/TypeTokenSpec.scala
semantics/src/main/scala/aqua/semantics/expr/CallArrowSem.scala
semantics/src/main/scala/aqua/semantics/expr/FuncSem.scala
semantics/src/main/scala/aqua/semantics/expr/ReturnSem.scala
semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
types/src/main/scala/aqua/types/CompareTypes.scala
types/src/main/scala/aqua/types/Type.scala

Return many values from a single function

---

backend/air/src/main/scala/aqua/backend/air/AirBackend.scala
backend/air/src/main/scala/aqua/backend/air/FuncAirGen.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptBackend.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
backend/src/main/scala/aqua/backend/Backend.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptBackend.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFile.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala
compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
model/src/main/scala/aqua/model/res/AquaRes.scala
model/src/main/scala/aqua/model/res/FuncRes.scala
model/src/main/scala/aqua/model/res/ServiceRes.scala
model/src/main/scala/aqua/model/transform/Transform.scala
model/test-kit/src/test/scala/aqua/model/transform/TransformSpec.scala

Provide better-prepared context for the client code generators.

Updating compiler backends

---

aqua-src/ret.aqua
aqua/error.aqua
aqua/service.aqua
cli/.jvm/src/main/scala/aqua/Test.scala
model/transform/src/main/scala/aqua/model/transform/res/AquaRes.scala
parser/src/main/scala/aqua/parser/head/UseExpr.scala
parser/src/main/scala/aqua/parser/lexer/Token.scala
parser/src/test/scala/aqua/parser/AbilityIdExprSpec.scala
parser/src/test/scala/aqua/parser/head/FromSpec.scala
parser/src/test/scala/aqua/parser/head/ImportFromSpec.scala
parser/src/test/scala/aqua/parser/head/ModuleSpec.scala
semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala

Imports bugfixes

---

backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala

JS: fix invalid imports (fixes #263)

---

aqua-src/import-empty.aqua
backend/.js/src/main/scala/aqua/backend/Version.scala
backend/.jvm/src/main/scala/aqua/backend/Version.scala
build.sbt
cli/.jvm/src/main/scala/aqua/Test.scala
parser/src/main/scala/aqua/parser/Parser.scala
parser/src/main/scala/aqua/parser/expr/RootExpr.scala
parser/src/main/scala/aqua/parser/lexer/Token.scala
parser/src/test/scala/aqua/parser/CoExprSpec.scala
project/plugins.sbt
semantics/src/main/scala/aqua/semantics/Semantics.scala

Fixes version display and empty module compilation (fixes #264 #265)

---

backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala

Add explicit any types to satisfy typescript compiler

---

aqua-src/export.aqua
aqua-src/import.aqua
semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala

Fix wildcard declaration

---

backend/js/src/main/scala/aqua/backend/js/JavaScriptCommon.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptCommon.scala

Fix type convertion for option type

---

aqua-src/import.aqua
backend/js/src/main/scala/aqua/backend/js/JavaScriptCommon.scala
cli/src/main/scala/aqua/ErrorRendering.scala
model/src/main/scala/aqua/model/func/FuncCallable.scala
parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
parser/src/main/scala/aqua/parser/lift/FileSpan.scala
parser/src/main/scala/aqua/parser/lift/Span.scala

Fix incorrect resolving pushing stream from func to a value (#275)

---

README.md
cli/src/main/scala/aqua/AppOps.scala
cli/src/main/scala/aqua/AquaCli.scala
npm/readme.md

Readme updates

---

aqua-src/import-empty.aqua
aqua-src/import.aqua
build.sbt
cli/.jvm/src/main/scala/aqua/Test.scala
cli/.jvm/src/test/scala/WriteFileSpec.scala
cli/src/main/scala/aqua/AppOps.scala
cli/src/main/scala/aqua/AquaCli.scala
cli/src/main/scala/aqua/AquaPathCompiler.scala
cli/src/main/scala/aqua/files/AquaFileSources.scala

fixes #292 
fixes #290 
fixes #287

Use and export without `.aqua` extension, flag for a dry run, create output directories 

---

aqua-src/import.aqua
aqua-src/ret.aqua
cli/.jvm/src/main/scala/aqua/Test.scala
cli/.jvm/src/test/scala/WriteFileSpec.scala
cli/src/main/scala/aqua/AppOps.scala
cli/src/main/scala/aqua/AquaCli.scala
cli/src/main/scala/aqua/AquaPathCompiler.scala
cli/src/main/scala/aqua/ErrorRendering.scala
cli/src/main/scala/aqua/files/AquaFileSources.scala
parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
parser/src/main/scala/aqua/parser/head/FilenameExpr.scala
parser/src/main/scala/aqua/parser/lexer/Value.scala
parser/src/main/scala/aqua/parser/lift/FileSpan.scala
parser/src/main/scala/aqua/parser/lift/Span.scala

fixes #283 
fixes #290 
fixes #203 
fixes #189

Error formatting, fix dry run, fix aqua extensions in imports

---

backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
backend/js/src/main/scala/aqua/backend/js/JavaScriptService.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFile.scala
backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala
cli/.jvm/src/test/scala/SourcesSpec.scala
cli/src/main/scala/aqua/files/AquaFileSources.scala
compiler/src/main/scala/aqua/compiler/AquaCompiled.scala
compiler/src/main/scala/aqua/compiler/AquaCompiler.scala

Check service definition fields in TS and JS, fix functions and services count in output

---

aqua-src/import.aqua
parser/src/main/scala/aqua/parser/expr/ConstantExpr.scala
parser/src/main/scala/aqua/parser/lexer/Token.scala
semantics/src/main/scala/aqua/semantics/Levenshtein.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala

Add levenshtein distance to error messages, fix constant parsing

---

npm/index.js

Fix version flag

---

cli/src/main/scala/aqua/ErrorRendering.scala
parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala

#322 unclear error message if parentheses are missing

---

aqua-src/import-empty.aqua
cli/src/main/scala/aqua/AquaPathCompiler.scala

#337 Delete duplicated errors

---

cli/.js/src/main/scala/aqua/JsTypes.scala
cli/.js/src/main/scala/aqua/run/RunCommand.scala
cli/.js/src/main/scala/aqua/run/RunConfig.scala
cli/.js/src/main/scala/aqua/run/RunOpts.scala

#366 Add secret key option #373 Handle timeout errors

---

npm/package-lock.json
npm/package.json

list -g @fluencelabs/fluence
/Users/bebo/.nvm/versions/node/v14.16.0/lib
├─┬ @fluencelabs/aqua@0.5.0-246
│ └── @fluencelabs/fluence@0.15.0.    <--
├─┬ @fluencelabs/fldist@0.4.3
│ └── @fluencelabs/fluence@0.10.1
└── @fluencelabs/fluence@0.15.1

fluence to 0.15.1

---

cli/src/main/scala/aqua/AquaPathCompiler.scala
cli/src/main/scala/aqua/Prelude.scala

#400 builtin as a default import in compiler

---

cli/.jvm/src/main/scala/aqua/PlatformOpts.scala
types/src/main/scala/aqua/types/Type.scala
types/src/test/scala/aqua/types/TypeSpec.scala

The arrows just stopped processing the arguments. Fixed

#426 aqua does not generate correct getDataSrv

---

cli/.js/src/main/scala/aqua/dist/DistOpts.scala
npm/aqua/dist.aqua
npm/package-lock.json
npm/package.json

```
"mean-service": {
"name": "mean-service",
"modules": [
...
]
}
}
```
right now you need to duplicate the name two times. This PR make it simplier and get a name from an argument
`aqua dist ... --service mean-service ...`
and config:
```
"mean-service": {
"modules": [
...
]
}
}
```
```

Pass name to a script as argument

---

cli/.js/src/main/scala/aqua/js/FluenceEnvironment.scala
cli/.js/src/main/scala/aqua/network/NetworkOpts.scala
npm/package-lock.json
npm/package.json

add `env` option to aqua cli

---

aqua-src/so.aqua
cli/.jvm/src/main/scala/aqua/PlatformOpts.scala
cli/.jvm/src/main/scala/aqua/Test.scala
compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala
model/src/main/scala/aqua/model/OpModel.scala
model/src/main/scala/aqua/model/ValueModel.scala
model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala
model/transform/src/test/scala/aqua/model/transform/ModelBuilder.scala
model/transform/src/test/scala/aqua/model/transform/topology/TopologySpec.scala

427 topology bug

---

cli/.js/src/main/scala/aqua/ArgOpts.scala
cli/.js/src/main/scala/aqua/CommandBuilder.scala
cli/.js/src/main/scala/aqua/FuncCompiler.scala
cli/.js/src/main/scala/aqua/PlatformOpts.scala
cli/.js/src/main/scala/aqua/dist/DistOpts.scala
cli/.js/src/main/scala/aqua/ipfs/IpfsOpts.scala
cli/.js/src/main/scala/aqua/js/CallJsFunction.scala
cli/.js/src/main/scala/aqua/keypair/KeyPairOpts.scala
cli/.js/src/main/scala/aqua/network/NetworkOpts.scala
cli/.js/src/main/scala/aqua/run/FuncCaller.scala
cli/.js/src/main/scala/aqua/run/RunCommand.scala
cli/.js/src/main/scala/aqua/run/RunOpts.scala
cli/.js/src/main/scala/aqua/run/Runner.scala
cli/.js/src/main/scala/aqua/script/ScriptOpts.scala
cli/src/main/scala/aqua/Prelude.scala
npm/aqua/script.aqua
npm/package-lock.json
npm/package.json

Compile a function with primitive arguments to AIR and upload it to a node with `Script.add` function
Refactoring *Opts and function calls

Add, remove and list scheduled scripts

---

cli/.js/src/main/scala/aqua/ArgOpts.scala
cli/.js/src/main/scala/aqua/CommandBuilder.scala
cli/.js/src/main/scala/aqua/FuncCompiler.scala
cli/.js/src/main/scala/aqua/dist/DistOpts.scala
cli/.js/src/main/scala/aqua/ipfs/IpfsOpts.scala
cli/.js/src/main/scala/aqua/network/NetworkOpts.scala
cli/.js/src/main/scala/aqua/run/RunCommand.scala
cli/.js/src/main/scala/aqua/run/RunOpts.scala
cli/.js/src/main/scala/aqua/run/Runner.scala
cli/.js/src/main/scala/aqua/script/ScriptOpts.scala
npm/aqua/dist.aqua

`createService` and `addBlueprint` commands

---

aqua-src/closure.aqua
aqua-src/hack.aqua
build.sbt
cli/.js/src/main/scala/aqua/run/Runner.scala
cli/.js/src/main/scala/aqua/script/ScriptOpts.scala
cli/.jvm/src/main/scala/aqua/Test.scala
model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala
model/inline/src/main/scala/aqua/model/inline/TagInliner.scala
model/inline/src/main/scala/aqua/model/inline/state/Arrows.scala
model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala
model/raw/src/main/scala/aqua/raw/ops/RawTag.scala
model/res/src/main/scala/aqua/res/MakeRes.scala
model/src/main/scala/aqua/model/AquaContext.scala
model/src/main/scala/aqua/model/FuncArrow.scala
model/src/main/scala/aqua/model/OpModel.scala
model/transform/src/main/scala/aqua/model/transform/funcop/ErrorsCatcher.scala
model/transform/src/main/scala/aqua/model/transform/pre/FuncPreTransformer.scala
model/transform/src/main/scala/aqua/model/transform/topology/OpModelTreeCursor.scala
model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala
model/transform/src/test/scala/aqua/model/transform/TransformSpec.scala
parser/src/main/scala/aqua/parser/expr/func/ClosureExpr.scala
parser/src/test/scala/aqua/parser/ClosureExprSpec.scala
semantics/src/main/scala/aqua/semantics/expr/func/ClosureSem.scala
semantics/src/test/scala/aqua/semantics/ClosureSemSpec.scala

Capture and apply topology

---

cli/.js/src/main/scala/aqua/ArgOpts.scala
cli/.js/src/main/scala/aqua/CommandBuilder.scala
cli/.js/src/main/scala/aqua/ipfs/IpfsOpts.scala
cli/.js/src/main/scala/aqua/keypair/KeyPairOpts.scala
cli/.js/src/main/scala/aqua/remote/DistOpts.scala
cli/.js/src/main/scala/aqua/run/FuncCaller.scala
cli/.js/src/main/scala/aqua/run/RunCommand.scala
cli/.js/src/main/scala/aqua/run/RunConfig.scala
cli/.js/src/main/scala/aqua/run/RunOpts.scala
cli/.js/src/main/scala/aqua/run/Runner.scala
cli/.js/src/main/scala/aqua/script/ScriptOpts.scala
cli/src/main/scala/aqua/FluenceOpts.scala
model/transform/src/main/scala/aqua/model/transform/Transform.scala

add `--show-sk` flag to show secret key, make secret key mandatory in `deploy_service` command

`--show-sk` flag

---

model/inline/src/main/scala/aqua/model/inline/raw/ApplyLambdaRawInliner.scala
model/inline/src/test/scala/aqua/model/inline/RawValueInlinerSpec.scala

#473 Nested types bug fix

---

cli/src/main/scala/aqua/ErrorRendering.scala
npm/package-lock.json
npm/package.json
parser/src/main/scala/aqua/parser/expr/ArrowTypeExpr.scala
parser/src/test/scala/aqua/parser/ArrowTypeExprSpec.scala
semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala

#478 throw compilation error if service returns multiple results 

---

cli/.js/src/main/scala/aqua/js/FluenceJsTypes.scala
cli/.js/src/main/scala/aqua/run/FuncCaller.scala
cli/.js/src/main/scala/aqua/run/RunConfig.scala
cli/src/main/scala/aqua/FluenceOpts.scala
npm/package-lock.json
npm/package.json

#475 Verbose flag to show additional call info for `aqua run`

---

cli/src/main/scala/aqua/ErrorRendering.scala
semantics/src/main/scala/aqua/semantics/SemanticError.scala
semantics/src/main/scala/aqua/semantics/Semantics.scala
semantics/src/main/scala/aqua/semantics/rules/ReportError.scala
semantics/src/main/scala/aqua/semantics/rules/StackInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/types/TypesInterpreter.scala
semantics/src/test/scala/aqua/semantics/ArrowSemSpec.scala
semantics/src/test/scala/aqua/semantics/Utils.scala
types/src/main/scala/aqua/types/Type.scala

#484 Improve `type mismatch` error messages

---

cli/.js/src/main/scala/aqua/run/FuncCaller.scala
npm/package-lock.json
npm/package.json

#385 handle javascript exceptions

---

compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala
model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala
model/inline/src/main/scala/aqua/model/inline/TagInliner.scala
model/inline/src/test/scala/aqua/model/inline/ArrowInlinerSpec.scala
npm/package-lock.json
npm/package.json

#499 rename vars in for

---

backend/src/main/scala/aqua/backend/Backend.scala
build.sbt
cli/.js/src/main/scala/aqua/FuncCompiler.scala
cli/src/main/scala/aqua/AquaPathCompiler.scala
compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
compiler/src/main/scala/aqua/compiler/AquaCompilerConf.scala
compiler/src/main/scala/aqua/compiler/AquaParser.scala
compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala
language-server-api/src/main/scala/aqua/lsp/AquaLSP.scala
language-server-npm/aqua-lsp-api.d.ts
language-server-npm/package.json
model/raw/src/main/scala/aqua/raw/ConstantRaw.scala
model/transform/src/main/scala/aqua/model/transform/TransformConfig.scala
semantics/src/main/scala/aqua/semantics/CompilerState.scala
semantics/src/main/scala/aqua/semantics/Semantics.scala
semantics/src/main/scala/aqua/semantics/TokenInfo.scala
semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala
semantics/src/main/scala/aqua/semantics/lsp/TokenInfo.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesAlgebra.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesState.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesState.scala
semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala

DXJ-21 Save token definitions for LSP

---

model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala

Fix arguments renaming in functions

---

model/src/main/scala/aqua/model/ValueModel.scala

LNG-59 Fix lambda resolving

---

cli/.js/src/main/scala/aqua/FuncCompiler.scala

LNG-67 Find JSON service in imported files for `aqua run`

---

aqua-src/antithesis.aqua
cli/.jvm/src/main/scala/aqua/Test.scala
model/inline/src/main/scala/aqua/model/inline/RawValueInliner.scala
model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala
semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala
semantics/src/main/scala/aqua/semantics/expr/func/AssignmentSem.scala
semantics/src/main/scala/aqua/semantics/expr/func/ForSem.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesAlgebra.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala
semantics/src/main/scala/aqua/semantics/rules/names/NamesState.scala

Fixes LNG-63: introduced ShadowRaw

---

cli/.js/src/main/scala/aqua/js/FluenceJsTypes.scala

remove `CAESI` prefix in public key

Fix key pair creation

---

cli/.js/src/main/scala/aqua/ArgOpts.scala
cli/.js/src/main/scala/aqua/js/FluenceJsTypes.scala
cli/.js/src/main/scala/aqua/run/FuncCaller.scala
npm/package-lock.json

DXJ-99 trim function string in `aqua cli` and fix PeerConfig

---

.github/workflows/snapshot.yml
.github/workflows/tests.yml

- make "Update comment" job a step to save space in github actions summary
- use branch sha commit hash in name

chore: Small E2E tuning

---

build.sbt
parser/src/main/scala/aqua/parser/expr/FieldTypeExpr.scala
parser/src/main/scala/aqua/parser/expr/func/AssignmentExpr.scala
parser/src/main/scala/aqua/parser/lexer/TypeToken.scala

restrict streams in arrays and options
restrict streams in data fields
restrict assignment with empty collections

LNG-85 Streams restrictions in aqua

---

.github/renovate.json
.github/workflows/e2e.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Please enable `e2e / status` as required check in repo settings

chore(ci): Notify on release failures and other small CI changes [fixes FLU-222, FLU-194, FLU-41 and FLU-196]

---

model/inline/src/main/scala/aqua/model/inline/MakeStructRawInliner.scala
model/inline/src/main/scala/aqua/model/inline/TagInliner.scala
model/inline/src/main/scala/aqua/model/inline/raw/ApplyIntoCopyRawInliner.scala
model/src/main/scala/aqua/model/OpModel.scala

fix: Canonicalize variable in object creation or copy if variable is a stream

---

backend/air/src/main/scala/aqua/backend/air/AirGen.scala
model/inline/src/main/scala/aqua/model/inline/raw/ApplyFunctorRawInliner.scala
model/res/src/main/scala/aqua/res/MakeRes.scala

fix: Fix type for functor [fixes LNG-119]

---

backend/ts/src/main/scala/aqua/backend/OutputFunc.scala

refactor: Store generated AIR string in exorted constant

---

backend/air/src/main/scala/aqua/backend/air/Air.scala

feat: Remove bang in lambdas in AIR

---

integration-tests/aqua/examples/funcs.aqua
integration-tests/src/__test__/examples.spec.ts
integration-tests/src/examples/funcsCall.ts
model/inline/src/main/scala/aqua/model/inline/ArrowInliner.scala
model/raw/src/main/scala/aqua/raw/ops/RawTag.scala
semantics/src/main/scala/aqua/semantics/expr/func/ClosureSem.scala

Fix renaming to fix incorrect code generation for nested function passing.
Fix renaming of `AssignmentTag`.
Fix renaming inside `AssignmentTag`.

fix(compiler): Passed function is not handled correctly [LNG-260]

---

api/api-npm/index.d.ts

Make interface types more clear

feat(api): Refactor js api interfaces

---

integration-tests/lsp-aqua/types.aqua
integration-tests/package.json
integration-tests/src/__test__/lsp-types.spec.ts
language-server/language-server-api/.js/src/main/scala/aqua/lsp/OutputTypes.scala
language-server/language-server-api/.js/src/main/scala/aqua/lsp/ResultHelper.scala
language-server/language-server-api/.js/src/main/scala/aqua/lsp/TypeJs.scala
language-server/language-server-npm/aqua-lsp-api.d.ts

Add JS representation of types in compiler

feat(language-server): Add types for types in LSP API

---

api/api-npm/index.js
api/api/.js/src/main/scala/api/types/InputTypes.scala

fix(compiler): Change `noEmptyResponse` default to `true`

---

aqua-src/antithesis.aqua
integration-tests/aqua/examples/option.aqua
integration-tests/src/__test__/examples.spec.ts
integration-tests/src/examples/useOptionalCall.ts
model/inline/src/main/scala/aqua/model/inline/raw/CollectionRawInliner.scala
model/inline/src/test/scala/aqua/model/inline/CollectionRawInlinerSpec.scala

Catch errors that happen inside `?[...]` instruction

fix(compiler): Ordering in option inliner [LNG-351]
